# Generated by Django 4.2.20 on 2025-03-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="devise_souhaitee",
            field=models.CharField(
                choices=[
                    ("CFA", "CFA"),
                    ("EUR", "EUR"),
                    ("USD", "USD"),
                    ("GBP", "GBP"),
                    ("YEN", "YEN"),
                    ("CHF", "CHF"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="ma_devise",
            field=models.CharField(
                choices=[
                    ("CFA", "CFA"),
                    ("EUR", "EUR"),
                    ("USD", "USD"),
                    ("GBP", "GBP"),
                    ("YEN", "YEN"),
                    ("CHF", "CHF"),
                ],
                max_length=5,
            ),
        ),
    ]
