# Generated by Django 4.2.20 on 2025-03-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_offer_devise_souhaitee_alter_offer_ma_devise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="taux_souhaite",
            field=models.IntegerField(max_length=16),
        ),
    ]
