# Generated by Django 4.2.20 on 2025-03-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_offer_montant"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="quantite",
            field=models.IntegerField(default="0", max_length=16),
            preserve_default=False,
        ),
    ]
