# Generated by Django 4.2.20 on 2025-08-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_offer_quantite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="quantite",
            field=models.IntegerField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="offer",
            name="taux_souhaite",
            field=models.IntegerField(blank=True, max_length=16),
        ),
    ]
