# Generated by Django 4.2.20 on 2025-08-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_offer_quantite_alter_offer_taux_souhaite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer", name="quantite", field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="taux_souhaite",
            field=models.IntegerField(blank=True),
        ),
    ]
