# Generated by Django 4.2.20 on 2025-10-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_offer_quantite_alter_offer_taux_souhaite"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="document_agrement",
            field=models.ImageField(
                blank=True, null=True, upload_to="documents_agrement/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="numero_agrement",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="piece_identite",
            field=models.ImageField(
                blank=True, null=True, upload_to="pieces_identite/"
            ),
        ),
    ]
